# Generated by Django 5.0.6 on 2024-06-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformer',
            name='banner',
            field=models.ImageField(blank=True, default='google.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='transformer',
            name='operation_year',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
