# Generated by Django 5.0.6 on 2024-06-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformers', '0004_transformer_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformer',
            name='image_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
