# Generated by Django 5.0.6 on 2024-07-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformers', '0005_alter_transformer_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeriesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
            ],
        ),
    ]
