# Generated by Django 5.0.6 on 2024-07-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformers', '0006_timeseriesdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeseriesdata',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='timeseriesdata',
            name='value',
        ),
        migrations.AddField(
            model_name='timeseriesdata',
            name='timestamp_r',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='timeseriesdata',
            name='timestamp_s',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='timeseriesdata',
            name='timestamp_t',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='timeseriesdata',
            name='value_r',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='timeseriesdata',
            name='value_s',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='timeseriesdata',
            name='value_t',
            field=models.FloatField(default=0.0),
        ),
    ]
